const data = [
  {
    key: "1",
    value: "Downing Street1",
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "2",
    value: "Downing Street2",
    name: "Jim Green",
    age: 42,
    address: "London No. 1 Lake Park",
  },
  {
    key: "3",
    value: "Downing Street3",
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
  },
  {
    key: "4",
    value: "Downing Street4",
    name: "Jim Red",
    age: 32,
    address: "London No. 2 Lake Park",
  },
  {
    key: "5",
    value: "Downing Street5",
    name: "John Brown Red",
    age: 32,
    address: "Sidney No. 2 Lake Park",
  },
  {
    key: "6",
    value: "Downing Street6",
    name: "Jim Red",
    age: 32,
    address: "London No. 2 Lake Park",
  },
  {
    key: "7",
    value: "Downing Street7",
    name: "Jim Red",
    age: 32,
    address: "Sidney No. 2 Lake Park",
  },
  {
    key: "8",
    value: "Downing Street8",
    name: "Jim Red",
    age: 32,
    address: "London No. 2 Lake Park",
  },
  {
    key: "9",
    value: "Downing Street9",
    name: "John Brown",
    age: 32,
    address: "Sidney No. 2 Lake Park",
  },
  {
    key: "10",
    value: "Downing Street10",
    name: "Joe Red",
    age: 32,
    address: "New York No. 2 Lake Park",
  },
  {
    key: "11",
    value: "Downing Street11",
    name: "John Brown",
    age: 32,
    address: "London No. 2 Lake Park",
  },
  {
    key: "12",
    value: "Downing Street12",
    name: "Joe Red",
    age: 32,
    address: "London No. 2 Lake Park",
  },
  {
    key: "13",
    value: "Downing Street13",
    name: "Jim Red",
    age: 32,
    address: "New York No. 2 Lake Park",
  },
];

export default data;
